name: Builb Test and push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: rubenvdkamp


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build . -t $REPO_NAME/$IMAGE_NAME
    - name: run docker compose
      run: |
        docker compose --verbose up -d && sleep 5
    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: postman/collection.json
        environment: postman/environment.json
        reporters: cli
        iterationCount: 3

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}


    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push multi-arch docker image
      run: |
        docker buildx create --name multiarch --driver docker-container --bootstrap --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $REPO_NAME/$IMAGE_NAME:latest --push .
